-- MySQL Script generated by MySQL Workbench
-- 11/27/16 22:58:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smart-garden
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smart-garden
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smart-garden` DEFAULT CHARACTER SET utf8 ;
USE `smart-garden` ;

-- -----------------------------------------------------
-- Table `smart-garden`.`rau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-garden`.`rau` (
  `rau_id` VARCHAR(20) NOT NULL,
  `ten` VARCHAR(45) NOT NULL,
  `gioithieu` VARCHAR(200) NOT NULL,
  `saubenh` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`rau_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-garden`.`quytrinh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-garden`.`quytrinh` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `chuanbi` VARCHAR(1000) NOT NULL,
  `ngam_u_hat` VARCHAR(1000) NOT NULL,
  `gieohat` VARCHAR(1000) NOT NULL,
  `thuhoach` VARCHAR(1000) NOT NULL,
  `sauthuhoach` VARCHAR(1000) NOT NULL,
  `rau_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rau_quytrinh_idx` (`rau_id` ASC),
  CONSTRAINT `fk_rau_quytrinh`
    FOREIGN KEY (`rau_id`)
    REFERENCES `smart-garden`.`rau` (`rau_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-garden`.`chamsoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-garden`.`chamsoc` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `soluong` INT(11) NOT NULL,
  `quytrinh_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quytrinh_chamsoc_idx` (`quytrinh_id` ASC),
  CONSTRAINT `fk_quytrinh_chamsoc`
    FOREIGN KEY (`quytrinh_id`)
    REFERENCES `smart-garden`.`quytrinh` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-garden`.`dat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-garden`.`dat` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dinhduong` VARCHAR(200) NOT NULL,
  `doam_toithieu` INT(11) NOT NULL,
  `doam_toida` INT(11) NOT NULL,
  `tyletham` DOUBLE NOT NULL,
  `doph` DOUBLE NOT NULL,
  `rau_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rau_dat_idx` (`rau_id` ASC),
  CONSTRAINT `fk_rau_dat`
    FOREIGN KEY (`rau_id`)
    REFERENCES `smart-garden`.`rau` (`rau_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-garden`.`giaidoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-garden`.`giaidoan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(45) NOT NULL,
  `thoigian` INT(11) NOT NULL,
  `chamsoc_id` INT(11) NOT NULL,
  `phanbon` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chamsoc_giaidoan_idx` (`chamsoc_id` ASC),
  CONSTRAINT `fk_chamsoc_giaidoan`
    FOREIGN KEY (`chamsoc_id`)
    REFERENCES `smart-garden`.`chamsoc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-garden`.`nuoctuoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-garden`.`nuoctuoi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `solan` INT(11) NOT NULL,
  `giaidoan_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_giaidoan_nuoctuoi_idx` (`giaidoan_id` ASC),
  CONSTRAINT `fk_giaidoan_nuoctuoi`
    FOREIGN KEY (`giaidoan_id`)
    REFERENCES `smart-garden`.`giaidoan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-garden`.`lantuoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-garden`.`lantuoi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `thoigian` INT(11) NOT NULL,
  `luongnuoc` INT(11) NOT NULL,
  `loaivoituoi` VARCHAR(45) NOT NULL,
  `nuoctuoi_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nuoctuoi_lantuoi_idx` (`nuoctuoi_id` ASC),
  CONSTRAINT `fk_nuoctuoi_lantuoi`
    FOREIGN KEY (`nuoctuoi_id`)
    REFERENCES `smart-garden`.`nuoctuoi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-garden`.`thoi_tiet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-garden`.`thoi_tiet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `anhsang` VARCHAR(200) NOT NULL,
  `nhietdo_thapnhat` INT(11) NOT NULL,
  `nhietdo_caonhat` INT(11) NOT NULL,
  `gio` VARCHAR(200) NOT NULL,
  `rau_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rau_idx` (`rau_id` ASC),
  CONSTRAINT `fk_rau_thoitiet`
    FOREIGN KEY (`rau_id`)
    REFERENCES `smart-garden`.`rau` (`rau_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
